GET http://localhost:4000/products?search=유리&sort=recent

###
GET http://localhost:4000/products/66e247ac889cd6be7c316533

###
POST http://localhost:4000/products
Content-Type: application/json

{
    "name": "유리구두",
    "description": "신데렐라가 되어보자",
    "price": 2000000000
}

###
PATCH http://localhost:4000/products/66e278daa80cbcc246f8b28d
Content-Type: application/json

{
    "tag": ["유리", "홈카페"]
}


###
DELETE  http://localhost:4000/products/66e256f05e0e974e6a41fb50