GET http://localhost:4000/products

###
GET http://localhost:4000/products/

###
POST http://localhost:4000/products
Content-Type: application/json

{
    "name": "Yozm",
    "description": "그릭 요거트",
    "price": 6000,
    "favoriteCount": 2
}

###
PATCH http://localhost:4000/products/66e247ac889cd6be7c316533
Content-Type: application/json

{
    "name": "어쩌고",
    "description": "저쩌고"
}


###
DELETE  http://localhost:4000/products/66e2eb416a7a05b80c25f131