export default {
  singleQuote: true,
  semi: true,
  useTabs: false,
  tabWidth: 2,
  trailingComma: 'all',
  printWidth: 130,
  arrowParens: 'avoid',
  bracketSpacing: true,
  endOfLine: 'auto',

  plugins: ['@trivago/prettier-plugin-sort-imports'],
  importOrder: [
    '^#configs/(.*)$',
    '^#connection/(.*)$',
    '^#containers/(.*)$',
    '^#controllers/(.*)$',
    '^#interfaces/(.*)$',
    '^#middlewares/(.*)$',
    '^#repositories/(.*)$',
    '^#routes/(.*)$',
    '^#services/(.*)$',
    '^#types/(.*)$',
    '^#utils/(.*)$',
    '^@/(.*)$',
    '^[./]',
  ],
  importOrderSortSpecifiers: true,
};
