POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "맥북",
  "description": "맥북이에요",
  "price": 2000000,
  "tags": ["전자제품"]
}

###

GET http://localhost:3000/products/66f16563fd8eb81296bd921c

###

PATCH http://localhost:3000/products/66f16563fd8eb81296bd921c
Content-Type: application/json

{
  "name": "Samsung",
  "description": "Samsung 에어컨"
}

###

DELETE http://localhost:3000/products/66f141891052044ecb9792e6

###s

GET http://localhost:3000/products?page=1&pageSize=3&sort=recent
