GET http://localhost:4000/products
###
GET http://localhost:4000/products?search=선풍기
###
GET http://localhost:4000/products?sort=recent&count=3
###
GET http://localhost:4000/products/66dfb79bcebb0a8d2821b156
###
POST http://localhost:4000/products
Content-Type: application/json

{
    "name": "미니 선풍기",
    "description" : "더운 날씨에 들고 다니기 좋은 미니 선풍기",
    "price": "3000",
    "tags": ["선풍기", "여름"]
}
###
PATCH http://localhost:4000/products/66dfea9b96b760192e08856d
Content-Type: application/json

{
    "price": "2000"
}
###
DELETE http://localhost:4000/products/66dfdd80fe233a4b9ad16a10