GET http://localhost:3000/products/66e1555f39d3bd1dc529dd24
###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "IPHONE 16",
  "price": "300000",
  "description": "최신 아이폰입니다!",
  "tags": ["아이폰"]
}
###
PATCH http://localhost:3000/products
Content-Type: application/json

{
  "name": "Samsung Galuxy book",
  "price": "160000",
  "description": "samsung 노트북 사용하세요~",
  "tags": ["노트북"]
}
###
DELETE http://localhost:3000/products/66e1555f39d3bd1dc529dd24
###
GET http://localhost:3000/products?page=2&limit=5&sort=recent


