
GET http://localhost:3000/articles

###
GET http://localhost:3000/articles/523e4567-e89b-12d3-a456-426614174004

###
GET http://localhost:3000/articles?orderBy=oldest

###
GET http://localhost:3000/articles?orderBy=recent&page=1&pageSize=2

###
GET http://localhost:3000/articles?keyword=중고거래

###
POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "추가4된 게시글 제목",
  "content": "추가4된 게시글 컨텐츠 내용입니다."
}

###
PATCH  http://localhost:3000/articles/0c215d64-524a-4d45-922f-3bd2a62e28d6
Content-Type: application/json

{
  "title": "수정된 게시글 제목",
  "content": "수정된 게시글 컨텐츠 내용입니다."
}

###
DELETE http://localhost:3000/articles/823000f0-a9e2-412f-bfd5-9d23c43c057a

###
GET http://localhost:3000/articles/99868427-fd04-4e63-87e1-0330d66249


###
POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": 133,
  "content": "오류 유발 컨텐츠."
}