GET http://localhost:3000/articles/b8f11e76-0a9e-4b3f-bccf-8d9b4fbf331e

###

GET http://localhost:3000/articles?offset=0&limit=10&order=recent

###

POST http://localhost:3000/articles
Content-Type: application/json

{
    "title": "첫댓글",
    "content": "처음으로 댓글 달아봅니다."
}

###

PATCH http://localhost:3000/articles/b8f11e76-0a9e-4b3f-bccf-8d9b4fbf331e
Content-Type: application/json

{
  "title": "댓글 수정",
  "content": "댓글 수정해봐요."
}

###

DELETE http://localhost:3000/articles/b8f11e76-0a9e-4b3f-bccf-8d9b4fbf331e
