GET http://localhost:3000/products

###

GET http://localhost:3000/products/b8f11e76-0a9e-4b3f-bccf-8d9b4fbf331e

###

POST http://localhost:3000/products
Content-Type: application/json

{
  "email": "yjkim@example.com", 
  "firstName": "유진",
  "lastName": "김",
  "address": "충청북도 청주시 북문로 210번길 5"
}

###

PATCH http://localhost:3000/products/b8f11e76-0a9e-4b3f-bccf-8d9b4fbf331e
Content-Type: application/json

{
  "address": "서울특별시 강남구 무실로 234번길 45-6"
}

###

DELETE http://localhost:3000/products/b8f11e76-0a9e-4b3f-bccf-8d9b4fbf331e
