
GET http://localhost:3000/products

###
GET http://localhost:3000/products/1e112c02-7c92-4d52-b76e-485e41e3f64d

###
GET http://localhost:3000/products?orderBy=oldest

###
GET http://localhost:3000/products?orderBy=recent&page=1&pageSize=2

###
GET http://localhost:3000/products?keyword=커피머신

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "신상품 111",
  "description": "신상품 111에 대한 설명입니다.",
  "category": "ELECTRONICS",
  "price": 100000,
  "stock": 10,
  "tags": ["태그는 5글자 이내여야 함", "신상", "할인"]
}

###
PATCH  http://localhost:3000/products/5f449bfe-4743-44e5-961e-6d0ea08b5e4e
Content-Type: application/json

{
  "name": "신상품 111 ",
  "description": "신상품 수정에 대한 설명입니다.",
  "price": 200000,
  "tags": ["수정태그1", "수정태그2"]
}

###
DELETE http://localhost:3000/products/dc027da1-2932-4bf9-8d4c-7866f00c5237

###
GET http://localhost:3000/products/dc027da1-2932-4bf9-8d4c-7866f00c5237