GET http://localhost:3000/products
###
GET http://localhost:3000/products?order=oldest&search=폰

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "테스트",
    "description": "하루죙일 테스트만함",
    "price": 20000,
    "tag": ["테스트임"],
  "image": [],
  "favoriteCount": 0
}

###
PATCH http://localhost:3000/products/00d9c3ca-bff0-4135-8868-b2b385d63272
Content-Type: application/json

{
    "name": "수정수정",
    "description": "수정가 10000원 할인",
    "price": 10000,
    "tag": ["수정 됐나요"],
  "image": [],
  "favoriteCount": 0
}


###
DELETE http://localhost:3000/products/61003e12-6381-419c-a9d3-5f54f3448f52