GET https://two-sprint-mission-be-t2e7.onrender.com/products

###

GET https://two-sprint-mission-be-t2e7.onrender.com/products?page=0&sort=recent&pageSize=10&keyword=갤


###

GET https://two-sprint-mission-be-t2e7.onrender.com/products/66e39a21e4682f0fbf4913c9


###

POST https://two-sprint-mission-be-t2e7.onrender.com/products
Content-Type: application/json

{
	"title": "강아지 산책",
	"description": "강아지랑 30분 산책하기"
}


###

PATCH https://two-sprint-mission-be-t2e7.onrender.com/products/66e39a21e4682f0fbf4913c9
Content-Type: application/json

{
	"name": "New 갤S21"
}


###

DELETE https://two-sprint-mission-be-t2e7.onrender.com/products/66e39a21e4682f0fbf4913c9
